apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: fe-app
    env: production
spec:
  type: ClusterIP
  selector:
    app: fe-app
    env: production
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    