apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be-app
    env: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: be-app
      env: production
  template:
    metadata:
      labels:
        app: be-app
        env: production
    spec:
      containers:
        - name: be-container
          image: kunalmane/mern-backend:v1
          ports:
            - containerPort: 3500
          envFrom:
            - secretRef:
                name: be-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3500
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3500
            initialDelaySeconds: 15
            periodSeconds: 5
