apiVersion: v1
kind: Service
metadata:
  name: be-app
  labels:
    app: be-app
    env: production
spec:
  type: ClusterIP
  selector:
    app: be-app
    env: production
  ports:
    - port: 3500
      targetPort: 3500
      protocol: TCP
