apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    env: production
spec:
  type: ClusterIP
  selector:
    app: mongo
    env: production
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-port