apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-app-pvc
  namespace: default
  labels:
    app: mongo
    env: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-storage
  resources:
    requests:
      storage: 8Gi
