apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-app-pv
  labels:
    app: mongo
    env: production
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storage
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
